const Products = [
    {
        id : 0,
        name : 'Lavis',
        imgURL : 'assets/images/t-shirt-01.jpg',
        price : '300',
        color : 'red',
        type : 'T-shirt',
        description: 'Google, LLC is an American multinational technology company that specializes in Internet-related services and products, which include online advertising technologies, a search engine, cloud computing, software, and hardware. It is considered one of the Big Five technology companies in the U.S. information technology industry, alongside Amazon, Facebook, Apple, and Microsoft.',
    },
    {
        id : 1,
        name : 'Jara Man',
        imgURL : 'assets/images/t shirt new1.jpg',
        price : '499',
        color : 'black',
        type : 'T-shirt',
        description: '',
    },
    {
        id : 2,
        name : 'Addidas',
        imgURL : 'assets/images/t shirt new2.jpg',
        price : '999',
        color : 'yellow',
        type : 'T-shirt',
        description: '',
    },
    {
        id : 3,
        name : 'Raymond',
        imgURL : 'assets/images/t shirt new3.jpg',
        price : '799',
        color : 'pink',
        type : 'T-shirt',
        description: '',
    },
    {
        id : 4,
        name : 'Jara Man',
        imgURL : 'assets/images/t shirt new4.jpg',
        price : '699',
        color : 'black',
        type : 'T-shirt',
        description: '',
    },
    {
        id : 5,
        name : 'Addidas',
        imgURL : 'assets/images/t shirt new5.jpg',
        price : '1199',
        color : 'green',
        type : 'T-shirt',
        description: '',
    },
    {
        id : 6,
        name : 'Jara Man',
        imgURL : 'assets/images/t shirt new6.jpg',
        price : '1999',
        color : 'blue',
        type : 'T-shirt',
        description: '',
    },
    {
        id : 7,
        name : 'Addidas',
        imgURL : 'assets/images/t shirt new7.jpg',
        price : '849',
        color : 'gray',
        type : 'T-shirt',
        description: '',
    },
    {
        id : 8,
        name : 'Raymond',
        imgURL : 'assets/images/t shirt new8.jpg',
        price : '2599',
        color : 'mixed',
        type : 'T-shirt',
        description: '',
    },
    
    
]

export default Products;